(cl:defpackage dialogflow_ros_msgs-msg
  (:use )
  (:export
   "<DIALOGFLOWCONTEXT>"
   "DIALOGFLOWCONTEXT"
   "<DIALOGFLOWEVENT>"
   "DIALOGFLOWEVENT"
   "<DIALOGFLOWPARAMETER>"
   "DIALOGFLOWPARAMETER"
   "<DIALOGFLOWREQUEST>"
   "DIALOGFLOWREQUEST"
   "<DIALOGFLOWRESULT>"
   "DIALOGFLOWRESULT"
  ))

