// Generated by gencpp from file gb_dialog/ActionMsg.msg
// DO NOT EDIT!


#ifndef GB_DIALOG_MESSAGE_ACTIONMSG_H
#define GB_DIALOG_MESSAGE_ACTIONMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gb_dialog
{
template <class ContainerAllocator>
struct ActionMsg_
{
  typedef ActionMsg_<ContainerAllocator> Type;

  ActionMsg_()
    : mode(0)
    , action()
    , data()  {
    }
  ActionMsg_(const ContainerAllocator& _alloc)
    : mode(0)
    , action(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _mode_type;
  _mode_type mode;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _action_type;
  _action_type action;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::gb_dialog::ActionMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gb_dialog::ActionMsg_<ContainerAllocator> const> ConstPtr;

}; // struct ActionMsg_

typedef ::gb_dialog::ActionMsg_<std::allocator<void> > ActionMsg;

typedef boost::shared_ptr< ::gb_dialog::ActionMsg > ActionMsgPtr;
typedef boost::shared_ptr< ::gb_dialog::ActionMsg const> ActionMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gb_dialog::ActionMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gb_dialog::ActionMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gb_dialog::ActionMsg_<ContainerAllocator1> & lhs, const ::gb_dialog::ActionMsg_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode &&
    lhs.action == rhs.action &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gb_dialog::ActionMsg_<ContainerAllocator1> & lhs, const ::gb_dialog::ActionMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gb_dialog

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gb_dialog::ActionMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gb_dialog::ActionMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gb_dialog::ActionMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gb_dialog::ActionMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gb_dialog::ActionMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gb_dialog::ActionMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gb_dialog::ActionMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d5e5c8f51b53e657059a1ed6ff38544d";
  }

  static const char* value(const ::gb_dialog::ActionMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd5e5c8f51b53e657ULL;
  static const uint64_t static_value2 = 0x059a1ed6ff38544dULL;
};

template<class ContainerAllocator>
struct DataType< ::gb_dialog::ActionMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gb_dialog/ActionMsg";
  }

  static const char* value(const ::gb_dialog::ActionMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gb_dialog::ActionMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 mode\n"
"string action\n"
"string data\n"
;
  }

  static const char* value(const ::gb_dialog::ActionMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gb_dialog::ActionMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
      stream.next(m.action);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActionMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gb_dialog::ActionMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gb_dialog::ActionMsg_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<int64_t>::stream(s, indent + "  ", v.mode);
    s << indent << "action: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.action);
    s << indent << "data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GB_DIALOG_MESSAGE_ACTIONMSG_H
