// Generated by gencpp from file dialogflow_ros_msgs/DialogflowResult.msg
// DO NOT EDIT!


#ifndef DIALOGFLOW_ROS_MSGS_MESSAGE_DIALOGFLOWRESULT_H
#define DIALOGFLOW_ROS_MSGS_MESSAGE_DIALOGFLOWRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <dialogflow_ros_msgs/DialogflowParameter.h>
#include <dialogflow_ros_msgs/DialogflowContext.h>

namespace dialogflow_ros_msgs
{
template <class ContainerAllocator>
struct DialogflowResult_
{
  typedef DialogflowResult_<ContainerAllocator> Type;

  DialogflowResult_()
    : action()
    , query_text()
    , fulfillment_text()
    , parameters()
    , contexts()
    , intent()  {
    }
  DialogflowResult_(const ContainerAllocator& _alloc)
    : action(_alloc)
    , query_text(_alloc)
    , fulfillment_text(_alloc)
    , parameters(_alloc)
    , contexts(_alloc)
    , intent(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _action_type;
  _action_type action;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _query_text_type;
  _query_text_type query_text;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _fulfillment_text_type;
  _fulfillment_text_type fulfillment_text;

   typedef std::vector< ::dialogflow_ros_msgs::DialogflowParameter_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::dialogflow_ros_msgs::DialogflowParameter_<ContainerAllocator> >::other >  _parameters_type;
  _parameters_type parameters;

   typedef std::vector< ::dialogflow_ros_msgs::DialogflowContext_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::dialogflow_ros_msgs::DialogflowContext_<ContainerAllocator> >::other >  _contexts_type;
  _contexts_type contexts;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _intent_type;
  _intent_type intent;





  typedef boost::shared_ptr< ::dialogflow_ros_msgs::DialogflowResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dialogflow_ros_msgs::DialogflowResult_<ContainerAllocator> const> ConstPtr;

}; // struct DialogflowResult_

typedef ::dialogflow_ros_msgs::DialogflowResult_<std::allocator<void> > DialogflowResult;

typedef boost::shared_ptr< ::dialogflow_ros_msgs::DialogflowResult > DialogflowResultPtr;
typedef boost::shared_ptr< ::dialogflow_ros_msgs::DialogflowResult const> DialogflowResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dialogflow_ros_msgs::DialogflowResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dialogflow_ros_msgs::DialogflowResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dialogflow_ros_msgs::DialogflowResult_<ContainerAllocator1> & lhs, const ::dialogflow_ros_msgs::DialogflowResult_<ContainerAllocator2> & rhs)
{
  return lhs.action == rhs.action &&
    lhs.query_text == rhs.query_text &&
    lhs.fulfillment_text == rhs.fulfillment_text &&
    lhs.parameters == rhs.parameters &&
    lhs.contexts == rhs.contexts &&
    lhs.intent == rhs.intent;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dialogflow_ros_msgs::DialogflowResult_<ContainerAllocator1> & lhs, const ::dialogflow_ros_msgs::DialogflowResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dialogflow_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dialogflow_ros_msgs::DialogflowResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dialogflow_ros_msgs::DialogflowResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dialogflow_ros_msgs::DialogflowResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dialogflow_ros_msgs::DialogflowResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dialogflow_ros_msgs::DialogflowResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dialogflow_ros_msgs::DialogflowResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dialogflow_ros_msgs::DialogflowResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7af2326075f5db031043836d68eb1ad3";
  }

  static const char* value(const ::dialogflow_ros_msgs::DialogflowResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7af2326075f5db03ULL;
  static const uint64_t static_value2 = 0x1043836d68eb1ad3ULL;
};

template<class ContainerAllocator>
struct DataType< ::dialogflow_ros_msgs::DialogflowResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dialogflow_ros_msgs/DialogflowResult";
  }

  static const char* value(const ::dialogflow_ros_msgs::DialogflowResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dialogflow_ros_msgs::DialogflowResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string action\n"
"string query_text\n"
"string fulfillment_text\n"
"DialogflowParameter[] parameters\n"
"DialogflowContext[] contexts\n"
"string intent\n"
"================================================================================\n"
"MSG: dialogflow_ros_msgs/DialogflowParameter\n"
"string param_name\n"
"string[] value\n"
"================================================================================\n"
"MSG: dialogflow_ros_msgs/DialogflowContext\n"
"string name\n"
"int32 lifespan_count\n"
"DialogflowParameter[] parameters\n"
;
  }

  static const char* value(const ::dialogflow_ros_msgs::DialogflowResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dialogflow_ros_msgs::DialogflowResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action);
      stream.next(m.query_text);
      stream.next(m.fulfillment_text);
      stream.next(m.parameters);
      stream.next(m.contexts);
      stream.next(m.intent);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DialogflowResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dialogflow_ros_msgs::DialogflowResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dialogflow_ros_msgs::DialogflowResult_<ContainerAllocator>& v)
  {
    s << indent << "action: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.action);
    s << indent << "query_text: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.query_text);
    s << indent << "fulfillment_text: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.fulfillment_text);
    s << indent << "parameters[]" << std::endl;
    for (size_t i = 0; i < v.parameters.size(); ++i)
    {
      s << indent << "  parameters[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::dialogflow_ros_msgs::DialogflowParameter_<ContainerAllocator> >::stream(s, indent + "    ", v.parameters[i]);
    }
    s << indent << "contexts[]" << std::endl;
    for (size_t i = 0; i < v.contexts.size(); ++i)
    {
      s << indent << "  contexts[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::dialogflow_ros_msgs::DialogflowContext_<ContainerAllocator> >::stream(s, indent + "    ", v.contexts[i]);
    }
    s << indent << "intent: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.intent);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DIALOGFLOW_ROS_MSGS_MESSAGE_DIALOGFLOWRESULT_H
