// Generated by gencpp from file dialogflow_ros_msgs/DialogflowEvent.msg
// DO NOT EDIT!


#ifndef DIALOGFLOW_ROS_MSGS_MESSAGE_DIALOGFLOWEVENT_H
#define DIALOGFLOW_ROS_MSGS_MESSAGE_DIALOGFLOWEVENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <dialogflow_ros_msgs/DialogflowParameter.h>

namespace dialogflow_ros_msgs
{
template <class ContainerAllocator>
struct DialogflowEvent_
{
  typedef DialogflowEvent_<ContainerAllocator> Type;

  DialogflowEvent_()
    : event_name()
    , parameters()  {
    }
  DialogflowEvent_(const ContainerAllocator& _alloc)
    : event_name(_alloc)
    , parameters(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _event_name_type;
  _event_name_type event_name;

   typedef std::vector< ::dialogflow_ros_msgs::DialogflowParameter_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::dialogflow_ros_msgs::DialogflowParameter_<ContainerAllocator> >::other >  _parameters_type;
  _parameters_type parameters;





  typedef boost::shared_ptr< ::dialogflow_ros_msgs::DialogflowEvent_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dialogflow_ros_msgs::DialogflowEvent_<ContainerAllocator> const> ConstPtr;

}; // struct DialogflowEvent_

typedef ::dialogflow_ros_msgs::DialogflowEvent_<std::allocator<void> > DialogflowEvent;

typedef boost::shared_ptr< ::dialogflow_ros_msgs::DialogflowEvent > DialogflowEventPtr;
typedef boost::shared_ptr< ::dialogflow_ros_msgs::DialogflowEvent const> DialogflowEventConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dialogflow_ros_msgs::DialogflowEvent_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dialogflow_ros_msgs::DialogflowEvent_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dialogflow_ros_msgs::DialogflowEvent_<ContainerAllocator1> & lhs, const ::dialogflow_ros_msgs::DialogflowEvent_<ContainerAllocator2> & rhs)
{
  return lhs.event_name == rhs.event_name &&
    lhs.parameters == rhs.parameters;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dialogflow_ros_msgs::DialogflowEvent_<ContainerAllocator1> & lhs, const ::dialogflow_ros_msgs::DialogflowEvent_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dialogflow_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dialogflow_ros_msgs::DialogflowEvent_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dialogflow_ros_msgs::DialogflowEvent_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dialogflow_ros_msgs::DialogflowEvent_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dialogflow_ros_msgs::DialogflowEvent_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dialogflow_ros_msgs::DialogflowEvent_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dialogflow_ros_msgs::DialogflowEvent_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dialogflow_ros_msgs::DialogflowEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "86c638660c5df1b57b9ebd900d18906f";
  }

  static const char* value(const ::dialogflow_ros_msgs::DialogflowEvent_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x86c638660c5df1b5ULL;
  static const uint64_t static_value2 = 0x7b9ebd900d18906fULL;
};

template<class ContainerAllocator>
struct DataType< ::dialogflow_ros_msgs::DialogflowEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dialogflow_ros_msgs/DialogflowEvent";
  }

  static const char* value(const ::dialogflow_ros_msgs::DialogflowEvent_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dialogflow_ros_msgs::DialogflowEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string event_name\n"
"DialogflowParameter[] parameters\n"
"================================================================================\n"
"MSG: dialogflow_ros_msgs/DialogflowParameter\n"
"string param_name\n"
"string[] value\n"
;
  }

  static const char* value(const ::dialogflow_ros_msgs::DialogflowEvent_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dialogflow_ros_msgs::DialogflowEvent_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.event_name);
      stream.next(m.parameters);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DialogflowEvent_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dialogflow_ros_msgs::DialogflowEvent_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dialogflow_ros_msgs::DialogflowEvent_<ContainerAllocator>& v)
  {
    s << indent << "event_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.event_name);
    s << indent << "parameters[]" << std::endl;
    for (size_t i = 0; i < v.parameters.size(); ++i)
    {
      s << indent << "  parameters[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::dialogflow_ros_msgs::DialogflowParameter_<ContainerAllocator> >::stream(s, indent + "    ", v.parameters[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DIALOGFLOW_ROS_MSGS_MESSAGE_DIALOGFLOWEVENT_H
