// Generated by gencpp from file dialogflow_ros_msgs/DialogflowService.msg
// DO NOT EDIT!


#ifndef DIALOGFLOW_ROS_MSGS_MESSAGE_DIALOGFLOWSERVICE_H
#define DIALOGFLOW_ROS_MSGS_MESSAGE_DIALOGFLOWSERVICE_H

#include <ros/service_traits.h>


#include <dialogflow_ros_msgs/DialogflowServiceRequest.h>
#include <dialogflow_ros_msgs/DialogflowServiceResponse.h>


namespace dialogflow_ros_msgs
{

struct DialogflowService
{

typedef DialogflowServiceRequest Request;
typedef DialogflowServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DialogflowService
} // namespace dialogflow_ros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dialogflow_ros_msgs::DialogflowService > {
  static const char* value()
  {
    return "70029259094fc3123850886da266641c";
  }

  static const char* value(const ::dialogflow_ros_msgs::DialogflowService&) { return value(); }
};

template<>
struct DataType< ::dialogflow_ros_msgs::DialogflowService > {
  static const char* value()
  {
    return "dialogflow_ros_msgs/DialogflowService";
  }

  static const char* value(const ::dialogflow_ros_msgs::DialogflowService&) { return value(); }
};


// service_traits::MD5Sum< ::dialogflow_ros_msgs::DialogflowServiceRequest> should match
// service_traits::MD5Sum< ::dialogflow_ros_msgs::DialogflowService >
template<>
struct MD5Sum< ::dialogflow_ros_msgs::DialogflowServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dialogflow_ros_msgs::DialogflowService >::value();
  }
  static const char* value(const ::dialogflow_ros_msgs::DialogflowServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dialogflow_ros_msgs::DialogflowServiceRequest> should match
// service_traits::DataType< ::dialogflow_ros_msgs::DialogflowService >
template<>
struct DataType< ::dialogflow_ros_msgs::DialogflowServiceRequest>
{
  static const char* value()
  {
    return DataType< ::dialogflow_ros_msgs::DialogflowService >::value();
  }
  static const char* value(const ::dialogflow_ros_msgs::DialogflowServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dialogflow_ros_msgs::DialogflowServiceResponse> should match
// service_traits::MD5Sum< ::dialogflow_ros_msgs::DialogflowService >
template<>
struct MD5Sum< ::dialogflow_ros_msgs::DialogflowServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dialogflow_ros_msgs::DialogflowService >::value();
  }
  static const char* value(const ::dialogflow_ros_msgs::DialogflowServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dialogflow_ros_msgs::DialogflowServiceResponse> should match
// service_traits::DataType< ::dialogflow_ros_msgs::DialogflowService >
template<>
struct DataType< ::dialogflow_ros_msgs::DialogflowServiceResponse>
{
  static const char* value()
  {
    return DataType< ::dialogflow_ros_msgs::DialogflowService >::value();
  }
  static const char* value(const ::dialogflow_ros_msgs::DialogflowServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DIALOGFLOW_ROS_MSGS_MESSAGE_DIALOGFLOWSERVICE_H
