// Generated by gencpp from file dialogflow_ros_msgs/DialogflowServiceRequest.msg
// DO NOT EDIT!


#ifndef DIALOGFLOW_ROS_MSGS_MESSAGE_DIALOGFLOWSERVICEREQUEST_H
#define DIALOGFLOW_ROS_MSGS_MESSAGE_DIALOGFLOWSERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dialogflow_ros_msgs
{
template <class ContainerAllocator>
struct DialogflowServiceRequest_
{
  typedef DialogflowServiceRequest_<ContainerAllocator> Type;

  DialogflowServiceRequest_()
    : voice(false)
    , text()  {
    }
  DialogflowServiceRequest_(const ContainerAllocator& _alloc)
    : voice(false)
    , text(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _voice_type;
  _voice_type voice;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _text_type;
  _text_type text;





  typedef boost::shared_ptr< ::dialogflow_ros_msgs::DialogflowServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dialogflow_ros_msgs::DialogflowServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DialogflowServiceRequest_

typedef ::dialogflow_ros_msgs::DialogflowServiceRequest_<std::allocator<void> > DialogflowServiceRequest;

typedef boost::shared_ptr< ::dialogflow_ros_msgs::DialogflowServiceRequest > DialogflowServiceRequestPtr;
typedef boost::shared_ptr< ::dialogflow_ros_msgs::DialogflowServiceRequest const> DialogflowServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dialogflow_ros_msgs::DialogflowServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dialogflow_ros_msgs::DialogflowServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dialogflow_ros_msgs::DialogflowServiceRequest_<ContainerAllocator1> & lhs, const ::dialogflow_ros_msgs::DialogflowServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.voice == rhs.voice &&
    lhs.text == rhs.text;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dialogflow_ros_msgs::DialogflowServiceRequest_<ContainerAllocator1> & lhs, const ::dialogflow_ros_msgs::DialogflowServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dialogflow_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dialogflow_ros_msgs::DialogflowServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dialogflow_ros_msgs::DialogflowServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dialogflow_ros_msgs::DialogflowServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dialogflow_ros_msgs::DialogflowServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dialogflow_ros_msgs::DialogflowServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dialogflow_ros_msgs::DialogflowServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dialogflow_ros_msgs::DialogflowServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6a0f44890f843243fefe4cc775c82cf7";
  }

  static const char* value(const ::dialogflow_ros_msgs::DialogflowServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6a0f44890f843243ULL;
  static const uint64_t static_value2 = 0xfefe4cc775c82cf7ULL;
};

template<class ContainerAllocator>
struct DataType< ::dialogflow_ros_msgs::DialogflowServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dialogflow_ros_msgs/DialogflowServiceRequest";
  }

  static const char* value(const ::dialogflow_ros_msgs::DialogflowServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dialogflow_ros_msgs::DialogflowServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool voice\n"
"string text\n"
;
  }

  static const char* value(const ::dialogflow_ros_msgs::DialogflowServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dialogflow_ros_msgs::DialogflowServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.voice);
      stream.next(m.text);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DialogflowServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dialogflow_ros_msgs::DialogflowServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dialogflow_ros_msgs::DialogflowServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "voice: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.voice);
    s << indent << "text: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.text);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DIALOGFLOW_ROS_MSGS_MESSAGE_DIALOGFLOWSERVICEREQUEST_H
